"""agente

Revision ID: 0627c995e813
Revises: 9e99911b95a0
Create Date: 2025-06-10 17:47:54.158079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0627c995e813'
down_revision: Union[str, None] = '9e99911b95a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agente_comunitario', sa.Column('senha', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'agente_comunitario', ['email'])
    op.create_unique_constraint(None, 'paciente', ['pa_email'])
    op.create_unique_constraint(None, 'profissional_saude', ['ps_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profissional_saude', type_='unique')
    op.drop_constraint(None, 'paciente', type_='unique')
    op.drop_constraint(None, 'agente_comunitario', type_='unique')
    op.drop_column('agente_comunitario', 'senha')
    # ### end Alembic commands ###
