"""Permitir data_inicio nulo

Revision ID: 8f9b475f051b
Revises: 0627c995e813
Create Date: 2025-06-10 20:10:36.142753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f9b475f051b'
down_revision: Union[str, None] = '0627c995e813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamento', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'profissional_saude', ['ps_registro_profissional'])
    op.create_unique_constraint(None, 'unidade_de_saude', ['un_nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidade_de_saude', type_='unique')
    op.drop_constraint(None, 'profissional_saude', type_='unique')
    op.alter_column('agendamento', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
