"""migração inicial

Revision ID: d9fef859eb76
Revises: 
Create Date: 2025-06-09 19:18:16.885507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fef859eb76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agente_comunitario',
    sa.Column('id_acs', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_acs'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_agente_comunitario_id_acs'), 'agente_comunitario', ['id_acs'], unique=False)
    op.create_table('paciente',
    sa.Column('pa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pa_cpf', sa.String(), nullable=False),
    sa.Column('pa_nome', sa.String(), nullable=False),
    sa.Column('pa_datanasc', sa.Date(), nullable=False),
    sa.Column('pa_telefone', sa.String(), nullable=False),
    sa.Column('pa_email', sa.String(), nullable=False),
    sa.Column('pa_senha', sa.String(), nullable=False),
    sa.Column('pa_endereco', sa.Text(), nullable=False),
    sa.Column('pa_historico', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pa_id'),
    sa.UniqueConstraint('pa_cpf')
    )
    op.create_index(op.f('ix_paciente_pa_id'), 'paciente', ['pa_id'], unique=False)
    op.create_table('profissional_saude',
    sa.Column('ps_id', sa.Integer(), nullable=False),
    sa.Column('ps_nome', sa.String(), nullable=False),
    sa.Column('ps_cpf', sa.String(), nullable=False),
    sa.Column('ps_especialidade', sa.String(), nullable=False),
    sa.Column('ps_email', sa.String(), nullable=False),
    sa.Column('ps_telefone', sa.String(), nullable=False),
    sa.Column('ps_registro_profissional', sa.String(), nullable=False),
    sa.Column('ps_senha', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ps_id'),
    sa.UniqueConstraint('ps_cpf')
    )
    op.create_index(op.f('ix_profissional_saude_ps_id'), 'profissional_saude', ['ps_id'], unique=False)
    op.create_table('unidade_de_saude',
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('un_nome', sa.String(), nullable=False),
    sa.Column('un_endereco', sa.Text(), nullable=False),
    sa.Column('tipo_unidade', sa.String(), nullable=False),
    sa.Column('contato', sa.Text(), nullable=False),
    sa.Column('orgao_respons', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_unidade')
    )
    op.create_index(op.f('ix_unidade_de_saude_id_unidade'), 'unidade_de_saude', ['id_unidade'], unique=False)
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('id_profissional', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('data_consulta', sa.Date(), nullable=False),
    sa.Column('hora_consulta', sa.Time(), nullable=False),
    sa.Column('status_consulta', sa.String(), nullable=False),
    sa.Column('tipo_consulta', sa.String(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('criada_por', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissional_saude.ps_id'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade_de_saude.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    op.create_index(op.f('ix_consulta_id_consulta'), 'consulta', ['id_consulta'], unique=False)
    op.create_table('agendamento',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_consulta', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_consulta'], ['consulta.id_consulta'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.pa_id'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_index(op.f('ix_agendamento_id_agendamento'), 'agendamento', ['id_agendamento'], unique=False)
    op.create_table('notificacao',
    sa.Column('id_notificacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_consulta', sa.Integer(), nullable=True),
    sa.Column('canal_comunicacao', sa.String(), nullable=True),
    sa.Column('tipo_notificacao', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_consulta'], ['consulta.id_consulta'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.pa_id'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    op.create_index(op.f('ix_notificacao_id_notificacao'), 'notificacao', ['id_notificacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacao_id_notificacao'), table_name='notificacao')
    op.drop_table('notificacao')
    op.drop_index(op.f('ix_agendamento_id_agendamento'), table_name='agendamento')
    op.drop_table('agendamento')
    op.drop_index(op.f('ix_consulta_id_consulta'), table_name='consulta')
    op.drop_table('consulta')
    op.drop_index(op.f('ix_unidade_de_saude_id_unidade'), table_name='unidade_de_saude')
    op.drop_table('unidade_de_saude')
    op.drop_index(op.f('ix_profissional_saude_ps_id'), table_name='profissional_saude')
    op.drop_table('profissional_saude')
    op.drop_index(op.f('ix_paciente_pa_id'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_agente_comunitario_id_acs'), table_name='agente_comunitario')
    op.drop_table('agente_comunitario')
    # ### end Alembic commands ###
